language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=lua5.3
    # - LUA=luajit

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - bash .travis/setup_uv.sh
  - bash .travis/setup_openssl.sh
  - luarocks install lluv --server=http://rocks.moonscript.org/dev UV_DIR=$TRAVIS_BUILD_DIR/libuv

install:
  - luarocks make rockspecs/lluv-ssl-scm-0.rockspec 

script: 
  - cd test
  - lua test.lua
  - lua test_large_chunk.lua 65535
  - lua test_large_chunk.lua 1048576
  - lua test_large_chunk.lua 16777216

# after_success:
#   - luacov-coveralls -j c.report.json

notifications:
  email:
    on_success: change
    on_failure: always
